# Faça um prgrama que leia um número inteiro
# qualquer e mostre na tela a sua tabuada
n = int(input('Digite um número inteiro: '))
print('{} X 0 = {}\n'.format(n,(n*0)))
print('{} X 1 = {}\n'.format(n,(n*1)))
print('{} X 2 = {}\n'.format(n,(n*2)))
print('{} X 3 = {}\n'.format(n,(n*3)))
print('{} X 4 = {}\n'.format(n,(n*4)))
print('{} X 5 = {}\n'.format(n,(n*5)))
print('{} X 6 = {}\n'.format(n,(n*6)))
print('{} X 7 = {}\n'.format(n,(n*7)))
print('{} X 8 = {}\n'.format(n,(n*8)))
print('{} X 9 = {}\n'.format(n,(n*9)))
print('{} X 10 = {}\n'.format(n,(n*10)))
print('-' * 12)
